version: '3.8'

services:

  postgres:
    image: postgres:17
    #container_name: postgres
    environment:
      POSTGRES_DB: PCT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Danny100
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    networks:
      - pctnet

  backend:
    build: ./backend
    tty: true
    command: >
      sh -c "python pct/manage.py makemigrations &&
             python pct/manage.py migrate &&
             python pct/manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: PCT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Danny100
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - pctnet

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
      - postgres
    networks:
      - pctnet

networks:
  pctnet:
volumes:
  postgresql_data:
