FROM python:3.12.2
WORKDIR /backend

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY .env ./
COPY pct ./

RUN cd pct
RUN python manage.py makemigrations
RUN python manage.py migrate

CMD ["python", "manage.py", "runserver"]
