import os
from dotenv import load_dotenv
load_dotenv()

# SERVER
SRV_SECRET_KEY = os.getenv("SRV_SECRET_KEY")
SRV_HOST = os.getenv("SRV_HOST")
SRV_CORS_ORIGIN_WHITELIST = os.getenv("SRV_CORS_ORIGIN_WHITELIST")

# DATABASES
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")

# DJOSER
DJ_DOMAIN = os.getenv("DJ_DOMAIN"),
DJ_PASSWORD_RESET_CONFIRM_URL = os.getenv("DJ_PASSWORD_RESET_CONFIRM_URL"),
DJ_USERNAME_RESET_CONFIRM_URL = os.getenv("DJ_USERNAME_RESET_CONFIRM_URL"),
DJ_ACTIVATION_URL = os.getenv("DJ_ACTIVATION_URL"),

# SMTP
SMTP_EMAIL_HOST_USER = os.getenv("SMTP_EMAIL_HOST_USER")
SMTP_EMAIL_HOST_PASSWORD = os.getenv("SMTP_EMAIL_HOST_PASSWORD")
SMTP_EMAIL_HOST = os.getenv("SMTP_EMAIL_HOST")
SMTP_EMAIL_PORT = os.getenv("SMTP_EMAIL_PORT")
SMTP_EMAIL_USE_TLS = os.getenv("SMTP_EMAIL_USE_TLS")
