# Generated by Django 5.1.1 on 2024-10-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
