# Generated by Django 5.1.1 on 2024-11-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
