# Generated by Django 5.1.1 on 2024-11-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_factory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='phone_company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
