# Generated by Django 5.1.1 on 2024-11-03 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABF', 'Принято фабрикой'), ('ABC', 'Добавлено заказчиком'), ('HIR', 'Принято в работу'), ('OHS', 'Заказ отгружен'), ('COM', 'Завершен')], max_length=100)),
                ('receiving_order', models.DateTimeField()),
                ('shipping_date', models.DateTimeField()),
                ('accepted_factory', models.DateTimeField()),
                ('xml', models.BinaryField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.factory')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.product')),
            ],
        ),
    ]
