# Generated by Django 5.1.1 on 2024-11-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_order_creator_at_order_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
