# Generated by Django 5.1.1 on 2024-11-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_order_product_alter_order_accepted_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ABF', 'Принято фабрикой'), ('ABC', 'Добавлено заказчиком'), ('HIR', 'Принято в работу'), ('OHS', 'Заказ отгружен'), ('COM', 'Завершен')], default='ABC', max_length=100),
        ),
    ]
