# Generated by Django 5.1.1 on 2024-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='xml',
            field=models.BinaryField(max_length=10000, null=True),
        ),
    ]
