# Generated by Django 5.1.1 on 2024-11-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_order_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_product',
            field=models.ManyToManyField(related_name='qp', through='application.QuantityProduct', to='application.product'),
        ),
    ]
