# Generated by Django 5.1.1 on 2024-11-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_order_accepted_factory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted_factory',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(default=None),
        ),
    ]
