# Generated by Django 5.1.1 on 2024-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_factory_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accepted_factory',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
