# Generated by Django 5.1.1 on 2024-11-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_order_accepted_factory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted_factory_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_date_status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
